#!/bin/bash

dest="$(git rev-parse --show-toplevel)/LICENSE"

function fetch_license()
{
  curl -o $dest https://raw.githubusercontent.com/lucperkins/licenses/master/$1.txt
}

case $1 in
  affero-gpl | affero)
    fetch_license affero
    ;;
  apache-v2 | apache)
    fetch_license apache-v2
    ;;
  artistic)
    fetch_license artistic
    ;;
  bsd-2-clause | bsd-2)
    fetch_license bsd-2-clause
    ;;
  bsd-3-clause | bsd-3)
    fetch_license bsd-3-clause
    ;;
  creative-commons | cc | c-c)
    fetch_license creative-commons
    ;;
  eclipse)
    fetch_license eclipse
    ;;
  gpl-v2)
    fetch_license gpl-v2
    ;;
  gpl-v3)
    fetch_license gpl-v3
    ;;
  lgpl-v2.1)
    fetch_license lgpl-v2
    ;;
  lgpl-v3)
    fetch_license lgp-v3
    ;;
  mit)
    fetch_license mit
    ;;
  mozilla)
    fetch_license mozilla
    ;;
  public-domain-cc0 | cc0)
    fetch_license public-domain-cc0
    ;;
  public-domain-unilicense | unilicense)
    fetch_license public-domain-unilicense
    ;;
  *)
    echo "
Available license names:

  affero-gpl | affero
  apache-v2 | apache
  artistic
  bsd-2-clause | bsd-2
  bsd-3-clause | bsd-3
  creative-commons | cc | c-c
  eclipse
  gpl-v2
  gpl-v3
  lgpl-v2.1
  lgpl-v3
  mit
  mozilla
  public-domain-cc0 | cc0
  public-domain-unilicense | unilicense

For more information, see http://choosealicense.com/licenses/
"
esac

if [ -f $dest ]; then
  git add $dest
fi
